Abi 2.4
tonlabs/ever-abi pull request #293
Opened 2023-08-01 09:55 UTC by AlexeyVavilin

2023-08-01 10:49 UTC, elasticLove1 requested changes

2023-08-01 10:49 UTC, elasticLove1 commented on CHANGELOG.md
> +- Param in fields section extended with `init: boolean`
Need to mention about breaking with removed `data` section

2023-08-01 10:49 UTC, elasticLove1 commented on CHANGELOG.md
> +- Param in fields section extended with `init: boolean`
Need to describe new features and breaking changes separately under

### New

### Breaking changes 

sections

2023-08-01 12:46 UTC, elasticLove1 requested changes
Waiting for support in Solidity, then release.

2023-08-02 09:37 UTC, IgorKoval commented on CHANGELOG.md
> +- - `ref(T)` – reference to a cell, cell is encoded as the default value of type `T`.
Зачем нам  `ref(T)`? Где и как мы его будем использовать?

2023-08-02 09:39 UTC, IgorKoval commented on docs/ABI.md
> +This section describes persistent smart contract data. Data structure is described as a list of variables names with corresponding data types and init flag. They are listed in the order in which they
`variables names` - это  корректно по-английски?

2023-08-03 09:55 UTC, IgorKoval commented on CHANGELOG.md
> +- `fixedbytes` – type is deprecated
Я вспомнил почему мы не использовали `fixedbytes<N>` в *abi.json для типа `bytesN` из Solidity.
`fixedbytes<N>` сохраняется в реф (так же как и `bytes`), что не очень эффективно для `fixedbytes<N>`. 
Предлагаю в этом же abi 2.4 сохранять `fixedbytes<N>` в ту же ячейку. Это ничего не сломает, так как `fixedbytes<N>` и так не используются в Solidity.

2023-11-09 15:45 UTC, IgorKoval approved these changes

2023-11-09 16:02 UTC, merged